apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-demo-auth
  namespace: aks-store
spec:
  podIdentity:
    provider:  azure-workload
    identityId: $MI_CLIENT_ID
    identityTenantId: $TENANT_ID
