apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-managed-prometheus-scalerns
  namespace: aks-store
spec:
  scaleTargetRef:
    name: store-front
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
  - type: prometheus
    metadata:
      serverAddress: $PROMETHEUS_SERVER
      metricName: nginx_ingress_controller_nginx_process_requests_total
      query: sum(rate(nginx_ingress_controller_nginx_process_requests_total[1m]))
      threshold: '1'
    authenticationRef:
      name: azure-demo-auth